# This is a basic workflow to help you get started with Actions

name: cron2

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
permissions:
  contents: write
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: ls -1

      - name: Configure Git user
        run: |
          echo "${GITHUB_ACTOR}"
          git config --global user.email "hugo.lpz@gmail.com"
          # "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "${GITHUB_ACTOR}"
        
      # Runs a set of commands using the runners shell
      - name: Add speakers via a multi-line script
        run: |
          echo "speakers" > speakers.json
          # Push changes to Github
          git add speakers.json
          git commit -m "Update speakers.json"
          git push origin main
       
      # Runs a set of commands using the runners shell
      - name: Add languages via a multi-line script
        run: |
          ./test.sh
          # Push changes to Github
          git add languages.json
          git commit -m "Update languages.json"
          git push origin main
